apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jmeter.fullname" . }}-master
{{- if .Values.annotations }}
  {{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "jmeter.name" . }}-master
    chart: {{ template "jmeter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
  {{ toYaml .Values.lables | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.config.master.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "jmeter.name" . }}-master
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "jmeter.name" . }}-master
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.config.allowOnePodPerNode }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "jmeter.name" . }}-master
                - {{ template "jmeter.name" . }}-slave
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- if .Values.config.agentpool }}
      nodeSelector:
        agentpool: {{ .Values.config.agentpool }}
      {{- end }}
      tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        operator: Exists
        effect: NoSchedule
      {{- if .Values.config.tolerateKey }}
      - key: {{ .Values.config.tolerateKey }}
        operator: Exists
        effect: NoSchedule
      {{- end }}
      containers:
      - name: {{ template "jmeter.name" . }}-master
        image: "{{ .Values.images.master.repo }}:{{ .Values.images.master.tag }}"
        imagePullPolicy: {{ .Values.images.master.pullPolicy }}
        env:
        - name: SSL_DISABLED
          value: "{{ .Values.config.disableSSL }}"
        - name: AUTO_RUN
          value: "{{ .Values.config.master.autoRunTests }}"
        - name: SLAVE_SVC_NAME
          value: "{{ template "jmeter.fullname" . }}-slave.{{ .Release.Namespace }}.svc.cluster.local"
        ports:
        - containerPort: 60000
          name: rmi-local-port
          protocol: TCP
        volumeMounts:
        {{- if .Values.config.master.storageClassName }}
        - name: test-volume
          mountPath: /test
        {{- end }}
      volumes:
        {{- if .Values.config.master.storageClassName }}
        - name: test-volume
          persistentVolumeClaim:
            claimName: jmeter-test-pvc
        {{- end }}
      {{- if .Values.imageCredentials.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.pullSecrets }}
      {{- end }}
      restartPolicy: {{ .Values.config.master.restartPolicy }}
